/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.java;

public class Printer {
    public void print(String text) {
//        if(text.isEmpty()) {
//            System.out.print("Hello Default!");
//        } else {
//            System.out.print(text);
//        }
    }
}
